version: '3'

# Base compose file, examples for specific cases are demonstrated
# in composer overrides in docker-composer.{example}.yml files. Run them with:
# docker-compose -f docker-compose.yml -f docker-composer.{example}.yml

services:
  sync-host-bind-volume:
    build: .
    restart: on-failure
    tmpfs:
      - /dvs/cache
    environment:
      - SYNC_VOLUME_NAME=data-host
      - SYNC_IGNORE_NAMES=entry*
      - SYNC_IGNORE_PATHS=.git
    volumes:
      - ${PWD}:/dvs/data

  sync-data-docker-volume:
    build: .
    restart: on-failure
    tmpfs:
      - /dvs/cache
    environment:
      - SYNC_VOLUME_NAME=data-docker
      - SYNC_UID=35
      - SYNC_GID=35
    volumes:
      - data:/dvs/data

  sync-demo:
    image: alpine
    tty: true
    command: ['/bin/sh', '-c', 'sleep 5s; while true ; do date;  ls -alsh /mnt/data ; sleep 5s; done']
    volumes:
      - data:/mnt/data

volumes:
  data: ~
