version: '3'

# You have to pass your read UID/GID when running this:
# HOST_UID=$(id -u) HOST_GID=$(id -g) docker-compose up --build

services:
  sync-host-bind-volume:
    environment:
      - SYNC_UID=${HOST_UID}
      - SYNC_GID=${HOST_GID}

